In [125]:
# importing the required libraries
import pandas as pd

In [126]:
# 1.	Write a Pandas program to read the given csv file.

dataSet = pd.read_csv("AfricaCupofNationsMatches.csv")

# 2. reading the first 7 rows of the dataset
first_7_rows = dataSet.head(7)
first_7_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

In [127]:
# 3. Select the desired columns
selected_columns = dataSet[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]

# Print the selected columns
selected_columns

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

In [128]:
# 4. selecting rows where egypt appears
egypt_rows = dataSet[(dataSet['HomeTeam'] == 'Egypt') | (dataSet['AwayTeam'] == 'Egypt') ]
egypt_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
7,1962,18-Jan-62,NaN,Egypt,Uganda,2.0,1.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
13,1963,24-Nov-63,NaN,Egypt,Nigeria,6.0,3.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN
14,1963,26-Nov-63,NaN,Egypt,Sudan,2.0,2.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN
16,1963,30-Nov-63,NaN,Egypt,Ethiopia,3.0,0.0,Third place match,NaN,Accra Sports Stadium,Accra,NaN

In [129]:
# 5. counting numbers of rows and columns
num_rows = dataSet.shape[0]
num_cols = dataSet.shape[1]
print("Number of rows:", num_rows)
print("Number of columns:", num_cols)

Number of rows: 622
Number of columns: 12

In [130]:
# 6. selecting rows where attendence is missing 
missing_attendance_rows = dataSet[dataSet['Attendance'].isnull()]
missing_attendance_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
10,1963,24-Nov-63,NaN,Ghana,Tunisia,1.0,1.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
11,1963,26-Nov-63,NaN,Ghana,Ethiopia,2.0,0.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
565,2017,29 January 2017 (2017-01-29),20:00,Egypt,Morocco,1.0,0.0,Quarter-finals,NaN,Stade de Port-Gentil,Port-Gentil,NaN
566,2017,1 February 2017 (2017-02-01),20:00,Burkina Faso,Egypt,1.0,1.0,Semi-finals,Egypt win on Penalities 3-4,Stade de l'Amitié,Libreville,NaN
567,2017,2 February 2017 (2017-02-02),20:00,Cameroon,Ghana,2.0,0.0,Semi-finals,NaN,Stade de Franceville,Franceville,NaN
568,2017,4 February 2017 (2017-02-04),20:00,Burkina Faso,Ghana,1.0,0.0,Third place play-off,NaN,Stade de Port-Gentil,Port-Gentil,NaN
569,2017,5 February 2017 (2017-02-05),20:00,Egypt,Cameroon,1.0,2.0,Final,NaN,Stade de l'Amitié,Libreville,NaN

In [131]:
# 7. Selecting the rows where 'HomeTeamGoals' are between 3 and 6 inclusive:
goals_rows = dataSet[(dataSet['HomeTeamGoals'] >= 3) & (dataSet['HomeTeamGoals'] <= 6)]
goals_rows

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
553,2017,20 January 2017 (2017-01-20),20:00,Morocco,Togo,3.0,1.0,Group C,NaN,Stade d'Oyem,Oyem,NaN
585,2019,27 June 2019 (2019-06-27),22:00,Kenya,Tanzania,3.0,2.0,Group C,NaN,30 June Stadium,Cairo,7233.0
595,2019,24 June 2019 (2019-06-24),22:00,Mali,Mauritania,4.0,1.0,Group E,NaN,Suez Stadium,Suez,6202.0
608,2019,6 July 2019 (2019-07-06),18:00,Nigeria,Cameroon,3.0,2.0,Round of 16,NaN,Alexandria Stadium,Alexandria,10000.0
611,2019,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0

In [132]:
# 8. Changing the "AwayTeamGoals" in the 3rd row to 10:
dataSet.loc[2, 'AwayTeamGoals'] = 10
dataSet

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [133]:
# 9. Sorting the DataFrame by 'HomeTeam' in ascending order, then by 'HomeTeamScores' in descending order:
sorted_df = dataSet.sort_values(by=['HomeTeam', 'HomeTeamGoals'], ascending=[True, False])
sorted_df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
205,1990,2-Mar-90,NaN,Algeria,Nigeria,5.0,1.0,Group A,NaN,Stade 5 Juillet 1962,Algiers,85000.0
29,1968,14-Jan-68,NaN,Algeria,Uganda,4.0,0.0,Group A,NaN,Hailé Sélassié Stadium,Addis Ababa,25000.0
135,1980,16-Mar-80,NaN,Algeria,Guinea,3.0,2.0,Group B,NaN,Liberty Stadium,Ibadan,20000.0
164,1984,5-Mar-84,NaN,Algeria,Malawi,3.0,0.0,Group B,NaN,Stade Bouaké,Bouaké,10000.0
171,1984,17-Mar-84,NaN,Algeria,Egypt,3.0,1.0,Third place match,NaN,Stade Félix Houphouët-Boigny,Abidjan,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
521,2012,12-Feb-12,20:30[note 1],Zambia,Ivory Coast,0.0,0.0,Final,Zambia win on Penalities 8-7,Stade d'Angondjé,Libreville,40000.0
549,2017,23 January 2017 (2017-01-23),20:00,Zimbabwe,Tunisia,2.0,4.0,Group B,NaN,Stade de l'Amitié,Libreville,NaN
398,2004,25-Jan-04,16:30,Zimbabwe,Egypt,1.0,2.0,Group C,NaN,Stade Taïeb El Mhiri,Sfax,22000.0
437,2006,23-Jan-06,20:00,Zimbabwe,Senegal,0.0,2.0,Group D,NaN,Port Said Stadium,Port Said,15000.0
575,2019,30 June 2019 (2019-06-30),21:00,Zimbabwe,DR Congo,0.0,4.0,Group A,NaN,30 June Stadium,Cairo,4364.0

In [134]:
# 10. Getting a list of DataFrame column headers:
column_headers = dataSet.columns.tolist()
print(column_headers)

['Year', 'Date ', 'Time ', 'HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals', 'Stage', 'SpecialWinConditions', 'Stadium', 'City', 'Attendance']

In [135]:
# 11. Appending a column of your choice to the DataFrame:
# creating a list of values to be added to the New Column
count = len(dataSet)
new_column = ["Column Values"] * count

# adding the values to the new column
if len(new_column) == len(dataSet):
    dataSet['NewColumn'] = new_column
else:
    print("Length of new_column does not match the DataFrame length.")
dataSet

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,NewColumn
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,Column Values
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,Column Values
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,Column Values
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,Column Values
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,Column Values
...,...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0,Column Values
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0,Column Values
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,Column Values
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,Column Values
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,Column Values

In [136]:
# 12. Adding 2 rows to the DataFrame:
# Specify the headers
headers = ['Year', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals', 'Stage',
           'SpecialWinConditions', 'Stadium', 'City', 'Attendance', 'NewColumn']

# Specify the new rows and store the values in a dictionary
new_row1 = {'Year': 2022, 'Date': '2022-01-01', 'Time': '15:00', 'HomeTeam': 'Team1', 'AwayTeam': 'Team2',
             'HomeTeamGoals': 2, 'AwayTeamGoals': 3, 'Stage': 'Group Stage', 'SpecialWinConditions': '',
             'Stadium': 'Stadium1', 'City': 'City1', 'Attendance': 50000, 'NewColumn': 1}
new_row2 = {'Year': 2022, 'Date': '2022-01-02', 'Time': '18:00', 'HomeTeam': 'Team3', 'AwayTeam': 'Team4',
             'HomeTeamGoals': 4, 'AwayTeamGoals': 1, 'Stage': 'Group Stage', 'SpecialWinConditions': '',
             'Stadium': 'Stadium2', 'City': 'City2', 'Attendance': 45000, 'NewColumn': 2}

# convert the dictionary to a dataframe and assing the index values
df1 = pd.DataFrame(new_row1, index=[count])
df2 = pd.DataFrame(new_row2, index=[count + 1])
#

# Concat dataframes
#
new_look = pd.concat([dataSet, df1])
dataSet = pd.concat([new_look, df2])
dataSet

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,NewColumn,Date,Time
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,Column Values,NaN,NaN
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,Column Values,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,Column Values,NaN,NaN
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,Column Values,NaN,NaN
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,Column Values,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,Column Values,NaN,NaN
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,Column Values,NaN,NaN
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,Column Values,NaN,NaN
622,2022,NaN,NaN,Team1,Team2,2.0,3.0,Group Stage,,Stadium1,City1,50000.0,1,2022-01-01,15:00
623,2022,NaN,NaN,Team3,Team4,4.0,1.0,Group Stage,,Stadium2,City2,45000.0,2,2022-01-02,18:00

In [138]:
# 13. Changing 'Uganda' to 'China' in the 'AwayTeam' column:
dataSet.loc[dataSet['AwayTeam'] == 'Uganda', 'AwayTeam'] = 'China'
dataSet

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,NewColumn,Date,Time
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,Column Values,NaN,NaN
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,Column Values,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,Column Values,NaN,NaN
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,Column Values,NaN,NaN
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,Column Values,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0,Column Values,NaN,NaN
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,Column Values,NaN,NaN
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,Column Values,NaN,NaN
622,2022,NaN,NaN,Team1,Team2,2.0,3.0,Group Stage,,Stadium1,City1,50000.0,1,2022-01-01,15:00
623,2022,NaN,NaN,Team3,Team4,4.0,1.0,Group Stage,,Stadium2,City2,45000.0,2,2022-01-02,18:00